### ISSUE TITLE
 hope you can answer my doubts when you see it.

### ISSUE THREAD

**Issue by WeirLisa** [rounak-meyur/optimal-incentive#2]
Dear author, I tried to study your article, but I found that some codes seem to lack running files, such as distev-30-adopt 4800 watts-seed-1234.txt. I hope you can answer my doubts when you see it.

**Comment by rounak-meyur** [comment]
Can you please indicate where is this file being called? -- the python code and the line number

**Comment by WeirLisa** [comment]
[](https://github.com/rounak-meyur/revs-admm/blob/23110c3c14e841d8ab44c599844c25a3e418fc20/test-dist-ind-adopt.py#L85).In lines 85-93 in the test-dist-ind-adopt.py file, # Get voltage for ADMM and # Get voltage for individual optimization two parts.Code are prefix = "distEV-"+str(adopt)+"-adopt"+str(int(rate))+"Watts-seed-"+str(j)+".txt"  and  prefix = "indEV-"+str(adopt)+"-adopt"+str(int(rate)) +"Watts-seed-"+str(j)+".txt".Thank you very much.

**Comment by rounak-meyur** [comment]
Please let me know if you can access the directory "out".

**Comment by rounak-meyur** [comment]
You need to change the "adoption" value in the "input_paramters" section (line 14) of the revs_config.yaml file and run the "test_optimizer.py" program. This will generate the results for the different adoption rates. I have added the "save=True" argument to the centralized and distributed optimization function calls and that should save the results in the respective directories. Try and let me know if this works for you. Sorry about the poor documentation, I will update it shortly.

**Comment by WeirLisa** [comment]
> You need to change the "adoption" value in the "input_paramters" section (line 14) of the revs_config.yaml file and run the "test_optimizer.py" program. This will generate the results for the different adoption rates. I have added the "save=True" argument to the centralized and distributed optimization function calls and that should save the results in the respective directories. Try and let me know if this works for you. Sorry about the poor documentation, I will update it shortly.

Ok, thank you very much for your guidance.
